version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
